_BASE_: "../Base-RCNN.yaml"
MODEL:
  WEIGHTS: "/Path/to/ImageNet/Pretrain/Weight"
  MASK_ON: False
  BACKBONE:
    WITHSAIA: False
    FREEZE_SAIA: False
  RESNETS:
    DEPTH: 101
  RPN:
    ENABLE_DECOUPLE: True
    BACKWARD_SCALE: 0.0
  ROI_HEADS:
    NUM_CLASSES: 15
    ENABLE_DECOUPLE: True
    BACKWARD_SCALE: 0.75
    NAME: "CommonalityROIHeads"
    OUTPUT_LAYER: "DoubleFastRCNNOutputLayers"
    MEMORY: False
  ROI_BOX_HEAD:
    BBOX_CLS_LOSS_TYPE: "CE"
INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
  MIN_SIZE_TEST: 800
DATASETS:
  TRAIN: ('voc_2007_trainval_base1', 'voc_2012_trainval_base1')
  TEST: ('voc_2007_test_base1',)
SOLVER:
  IMS_PER_BATCH: 32
  BASE_LR: 0.01
  STEPS: (10000, 13300)
  MAX_ITER: 15000
  CHECKPOINT_PERIOD: 200000
  WARMUP_ITERS: 100
OUTPUT_DIR: "/Path/to/Output/Dir"